pipeline {
    agent {label 'linux'}
    parameters {
        string(name: 'image-name', defaultvalue: 'msmapp')

        string(name: 'DHUser', defaultvalue: 'samsta')

        string(name: 'target-image', defaultvalue: 'dockerfile_image')
    }
    tools {
        nodejs 'node16.8.0'
    }
    stages {
        stage('clone app project') {
            steps {
                git branch: "main", url: "https://github.com/Sam-sta/AT-BC-LAT-01.git"
            }
        }

        stage('install dependencies') {
            steps {
                sh "npm install"
            }
        }

        stage('build app image') {
            steps {
                sh "docker build -t ${params.image-name}:$BUILD_NUMBER ."
            }
        }

        stage('docker-hub login') {
            steps {
                sh "docker login -u ${params.DHUser} --password-stdin"
            }
        }

        stage('tag image') {
            steps {
                sh "docker tag ${params.image-name}:$BUILD_NUMBER ${params.target-image}:${params.image-name}"
            }
        }
    }
}